### ISSUE TITLE
Copyright / License

### ISSUE THREAD

**Issue by whythecode** [biblys/isbn#2]
Hi @iwazaru, this looks great, thanks for sharing!!
Could you maybe add a copyright and license? Otherwise I can't use it :)
Cheers

**Comment by whythecode** [comment]
I see you set MIT in composer.json, but a full license disclaimer is safer :)

Ideally there would be a LICENSE file in the package, according to:
http://choosealicense.com/licenses/mit/

Plus disclaimers on each PHP class. something like:
```
/*
 * This file is part of the XYZ package.
 *
 * (c) yourname
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */
```

thanks in advance!

**Comment by iwazaru** [comment]
Hey @whythecode, I added the [MIT License](https://github.com/biblys/isbn/commit/d7c5fc6f78131aedbaf0b51e1281a3545c62dbe2) and the [copyright notice](https://github.com/biblys/isbn/commit/d93d72d0afcfcb354e9fe81eec73e604ddf8d766) onto the [develop branch](https://github.com/biblys/isbn/tree/develop), tell me if it looks good to you and I'll prepare a new release.

**Comment by whythecode** [comment]
hi @iwazaru, sorry, only saw this now! looks awesome, thanks, you rock ;)
