### ISSUE TITLE
Support for ISBN-A "actionable ISBN"

### ISSUE THREAD

**Issue by rlueder** [biblys/isbn#42]
@iwazaru Thank you for this library, I learned quite a bit about ISBN validation and formatting by reading your well-documented source code.

I'd like to suggest adding support for the ISBN-A format described here: [DOI System and the ISBN System](https://www.doi.org/factsheets/ISBN-A.html); and here's more information on [DOIs](https://en.wikipedia.org/wiki/Digital_object_identifier). Their documentation under "Syntax of ISBN-A" however is not clear as to where the prefix/suffix divider should be placed.

> The syntax specification, reading from left to right, is:
> - Handle System DOI name prefix = "10."
> - ISBN (GS1) Bookland prefix = "978." or "979."
> - ISBN registration group element and publisher prefix = variable length numeric string of 2 to 8 digits
> - Prefix/suffix divider = "/"
> - ISBN Title enumerator and checkdigit = maximum 6 digit title enumerator and 1 digit check digit.

As an example, I'm using the ISBN for a 2016 Penguin edition of [Neuromancer](https://www.google.com/books/edition/Neuromancer/pNQiDQAAQBAJ) (978-014311160-3) I know that other books in the series have a similar ISBN, for example [2001 A Space Odissey](https://www.google.com/books/edition/2001/NdQiDQAAQBAJ) (978-014311157-3) so for this particular case it seems that placing the divider after the `0143111` sequence is a somewhat decent guess. A ISBN-A for both books would then be `10.978.0143111/603` and `10.978.0143111/573` respectively.

The DOI website offers a "resolver" functionality on their homepage (under "Resolve a DOI name" ): https://www.doi.org/
but any of these seem valid: `10.978.0/143111603`, `10.978.0143111/603`, `10.978.014311160/3` etc.

From your experience with ISBN numbers is there a rule that can be determined for the position of the prefix/suffix divider? In case it can't be determined, it seems that placing the divider just before the checksum digit seems like a reasonable solution but perhaps not accurate by the specification.

Thanks!

**Comment by iwazaru** [comment]
Hey @rlueder!

ISBN-13 can be divided in five parts:

| - | ISBN Prefix | Registration group element | Publisher prefix | Title enumerator | Check digit |
| - | ----------- | ----------------------------| ----------------| ----------------| -----------|
| Neuromancer |978|0|14|311160|3|
| 2001 A Space Odyssey | 978|0|14|311157|3|

The rules to determine which part belongs to the registration group, the publisher prefix or the title enumerator are quite complex, but you can find the parsing logic expressed in [the `Parser` class](https://github.com/biblys/isbn/blob/main/src/Biblys/Isbn/Parser.php).

Anyway, as the docs you quoted states, the "/" divider should go between the publisher prefix and the title enumerator, ie for these two books :

- Neuromancer: 10.978.014/3111603
- 2001 A Space Odyssey: 10.978.014/3111573

Knowing this, it should be easy enough to implement a `formatAsIbsnA` (or `formatAsDoi`?) method in [the `Formatter` class](https://github.com/biblys/isbn/blob/main/src/Biblys/Isbn/Formatter.php). Want to give it a try?
