### ISSUE TITLE
newbie help

### ISSUE THREAD

**Issue by iandoug** [biblys/isbn#8]
Hi

Having some issues. Which version of PHP does this require?

It seems to install okay:

$ composer require biblys/isbn:~2.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing biblys/isbn (2.0.7): Downloading (100%)         
Writing lock file
Generating autoload files

but does not like "use" statement:

PHP Parse error:  syntax error, unexpected 'use' (T_USE) in /home/parsebook.php on line 444

Tried various workarounds without success. Did I miss a step somewhere?
Don't really use composer much.

thanks.

**Comment by iwazaru** [comment]
Hey @iandoug, today this library is only tested for PHP 5.6 & 7.0, which are both obsolete, because this hadn't be updated for while. I'll look into it. Can't you tell me which PHP version your are using?

**Comment by iwazaru** [comment]
Also, can you show me your code? I think you could be misusing "use".

**Comment by iandoug** [comment]
PHP 5.6.40

Copied and pasted from here, so was 
use Biblys\Isbn\Isbn as Isbn;

Workaround: moved the PHP files into same directory as my program, require them, and commented out namespace lines, at which point it works.

thanks, Ian

**Comment by iwazaru** [comment]
I'll close this as I don't think the problem comes from the package. Maybe this can help you understand what's going on with `use`:
https://stackoverflow.com/a/33355711/1053818
