### ISSUE TITLE
Improve error output

### ISSUE THREAD

**Issue by S1SYPHOS** [biblys/isbn#9]
Hey there,
I want to use your library, but one thing I stumbled upon was error message management: Is there an easy way to get *just* the actual error message (eg, ISBN too short)?

I guess it would be helpful to convert those to Exceptions, too. I want to replace some custom code I hacked together with your library, but don't know exactly how my error management could be committed to your project.

Cheers,
S1SYPHOS

**Comment by iwazaru** [comment]
Hi @S1SYPHOS,

You can use the `$isbn->getErrors()` methods to get the error message if the `$isbn->isValid()` method has returned `false`. Does that meet your needs?

Anyway, I agree using exceptions would be better. I don't want to introduce any breaking changes at this point, but I'm thinking a good way to do this would be add a `$isbn->validate()` method that would either return `true` or throw an exception.

**Comment by S1SYPHOS** [comment]
That sounds great! Let me know if I can lend a hand. I'm in need of a serious ISBN validation library right now, so I'd gladly contribute.

Do you see how `$isbn->validate()` could be introduced in a non-breaking way, alongside what you have right now? There might be duplicated code for now, but .. :grin:

**Comment by iwazaru** [comment]
By "non-breaking way", I meant adding a new method (here `validate`) instead of changing the existing `isValid` method.

Anyway, I think I found an easy way to do it, and added it to the [develop](https://github.com/biblys/isbn/tree/develop) branch. It would look like this:

```php
<?php

$ean = "9791091146098";
$isbn = new Isbn($ean);

try {
    $isbn->validate();
    $isbn13 = $isbn->format("ISBN-13");
    echo "ISBN-13: $isbn13";
} catch(Exception $e) {
    echo "An error occured while parsing $ean: ".$e->getMessage();
}
```

If it's okay for you, I'll publish a new release.

**Comment by S1SYPHOS** [comment]
Great workaround, checking for errors and if there aren't any, given ISBN/EAN is valid :+1: 
Let me know if you are going for "real" exceptions someday (I might even fork it and send a PR :grin:)

**Comment by iwazaru** [comment]
Not sure what you mean by "real" exceptions, so I'll be looking for your PR!
